//! GnuPG fixture regression and placeholder tests.
//! These checks validate captured fixture artifacts or document optional future fixtures
//! without crowding the core message-interoperability binary.

mod common;

use pgp_mobile::decrypt;
use pgp_mobile::encrypt;
use pgp_mobile::keys::{self, KeyProfile};

/// Generate a Profile B (v6) public key fixture for GnuPG rejection testing.
/// Run manually: `cargo test test_generate_v6_fixture -- --ignored`
/// Then run `generate_gpg_fixtures.sh` to test GnuPG import rejection.
#[test]
#[ignore]
fn test_generate_v6_fixture() {
    let key_b = keys::generate_key_with_profile(
        "Profile B Test".to_string(),
        Some("profile-b@example.com".to_string()),
        None,
        KeyProfile::Advanced,
    )
    .expect("Profile B key gen should succeed");

    assert_eq!(key_b.key_version, 6);

    let fixture_path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("profile_b_v6_pubkey.gpg");

    std::fs::write(&fixture_path, &key_b.public_key_data)
        .expect("Should write v6 public key fixture");

    println!(
        "Generated v6 fixture: {:?} ({} bytes)",
        fixture_path,
        key_b.public_key_data.len()
    );
}

/// C3.8: Verify that GnuPG rejection output was captured by fixture generation.
/// Requires running `test_generate_v6_fixture` (ignored) then `generate_gpg_fixtures.sh`.
#[test]
fn test_c3_8_gpg_rejection_output_recorded() {
    let fixture_path = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("gpg_v6_import_rejection.txt");

    if !fixture_path.exists() {
        eprintln!(
            "Skipping: gpg_v6_import_rejection.txt not found. \
             Run `cargo test test_generate_v6_fixture -- --ignored` then \
             `bash generate_gpg_fixtures.sh` to generate it."
        );
        return;
    }

    let content =
        std::fs::read_to_string(&fixture_path).expect("Should read rejection output file");

    assert!(
        !content.is_empty(),
        "GnuPG rejection output file must not be empty"
    );

    let has_error_indicators = content.contains("error")
        || content.contains("no valid OpenPGP data")
        || content.contains("not supported")
        || content.contains("unknown packet")
        || content.contains("gpg_import_exit_code=");

    assert!(
        has_error_indicators,
        "GnuPG rejection output should contain error indicators, got: {}",
        content
    );

    if let Some(line) = content
        .lines()
        .find(|l| l.starts_with("gpg_import_exit_code="))
    {
        let code = line.trim_start_matches("gpg_import_exit_code=").trim();
        assert_ne!(
            code, "0",
            "GnuPG must reject v6 key import with a non-zero exit code, got: {code}"
        );
    }
}

/// M10: Import and use an RSA-4096 key generated by GnuPG.
#[test]
#[ignore = "Requires RSA-4096 GnuPG fixture (run generate_gpg_fixtures.sh with RSA support)"]
fn test_c3_gpg_rsa_key_fixture_import() {
    let pubkey = common::load_fixture("gpg_rsa4096_pubkey.asc");
    let secretkey = common::load_fixture("gpg_rsa4096_secretkey.asc");

    let info = keys::parse_key_info(&pubkey).expect("Should parse RSA-4096 public key");
    assert_eq!(info.key_version, 4, "RSA key must be v4");
    assert_eq!(info.profile, KeyProfile::Universal);
    assert!(info.has_encryption_subkey, "Must have encryption subkey");

    let plaintext = b"RSA-4096 interop test";
    let ciphertext = encrypt::encrypt(plaintext, &[pubkey.clone()], None, None)
        .expect("Encrypt to RSA key should succeed");
    let result = decrypt::decrypt(&ciphertext, &[secretkey], &[pubkey])
        .expect("Decrypt with RSA key should succeed");
    assert_eq!(result.plaintext, plaintext);
}

/// L7: Import a revoked GnuPG key and verify revocation is detected.
#[test]
#[ignore = "Requires revoked GnuPG key fixture (run generate_gpg_fixtures.sh with revocation support)"]
fn test_c3_gpg_revoked_key_fixture() {
    let pubkey = common::load_fixture("gpg_revoked_pubkey.asc");

    let info = keys::parse_key_info(&pubkey).expect("Should parse revoked GnuPG key");
    assert_eq!(info.key_version, 4);
    assert!(
        info.is_revoked,
        "Key must be marked as revoked after importing revocation cert"
    );

    let plaintext = b"Should not encrypt to revoked key";
    let result = encrypt::encrypt(plaintext, &[pubkey], None, None);
    assert!(result.is_err(), "Encryption to revoked key should fail");
}
