//! Shared `sq` (sequoia-sq) harness for the live cross-tool interop tests.
//!
//! Mirrors `common/gnupg.rs`: an isolated `sq --home` per test plus a
//! probe-or-skip gate. The gate honors `CYPHERAIR_REQUIRE_SQ=1`: the
//! mandatory CI interop lane (`rust-gnupg-interop`, which brews sequoia-sq)
//! fails (does not silently pass) when sq is missing, while local/contributor
//! runs without sq skip cleanly. Fixtures generated by
//! `fixtures/generate_sq_fixtures.sh` keep the committed side deterministic.
#![allow(dead_code)]

use std::path::PathBuf;
use std::process::Command;

use tempfile::TempDir;

/// Resolve the `sq` binary by probing `sq version`, honoring the
/// skip-forbidden gate.
///
/// Returns `Some(path)` when sq is available. When sq is not found:
/// - with `CYPHERAIR_REQUIRE_SQ=1`, panics so a mandatory interop lane fails
///   instead of silently passing;
/// - otherwise returns `None` so the caller can skip (sq-less dev/CI runs).
pub fn require_sq_or_skip() -> Option<PathBuf> {
    match find_sq() {
        Some(path) => Some(path),
        None => {
            if sq_is_required() {
                panic!(
                    "CYPHERAIR_REQUIRE_SQ=1 but sq was not found on PATH or known locations; \
                     the mandatory sq interop lane must not skip"
                );
            }
            eprintln!(
                "sq not found on this system; skipping (set CYPHERAIR_REQUIRE_SQ=1 to forbid skips)"
            );
            None
        }
    }
}

fn sq_is_required() -> bool {
    std::env::var_os("CYPHERAIR_REQUIRE_SQ").is_some_and(|value| value == "1")
}

/// Search for a working `sq` binary: PATH first, then common Homebrew/system
/// paths. A candidate counts only if `sq version` actually runs.
pub fn find_sq() -> Option<PathBuf> {
    let mut candidates = vec![PathBuf::from("sq")];
    candidates.extend(
        ["/opt/homebrew/bin/sq", "/usr/local/bin/sq", "/usr/bin/sq"]
            .iter()
            .map(PathBuf::from),
    );

    for candidate in candidates {
        if let Ok(output) = Command::new(&candidate).arg("version").output() {
            if output.status.success() {
                return Some(candidate);
            }
        }
    }

    None
}

/// Create a temporary `sq --home` directory so tests never touch the user's
/// real cert store or key store.
pub fn setup_sq_home() -> TempDir {
    TempDir::new().expect("Failed to create temp sq home")
}

/// Create a `Command` for sq bound to the given isolated home.
pub fn sq_cmd(sq_path: &PathBuf, home: &TempDir) -> Command {
    let mut cmd = Command::new(sq_path);
    cmd.arg("--home").arg(home.path());
    cmd
}

/// Run an sq command to completion, asserting success and returning stdout.
pub fn run_sq(mut cmd: Command, context: &str) -> Vec<u8> {
    let output = cmd
        .output()
        .unwrap_or_else(|e| panic!("Failed to run sq ({context}): {e}"));
    assert!(
        output.status.success(),
        "sq {context} failed:\nstdout: {}\nstderr: {}",
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
    );
    output.stdout
}
