import Foundation

/// App-wide boot-safe configuration stored in UserDefaults.
@Observable
final class AppConfiguration {
    private let defaults: UserDefaults

    /// Private-key control state. The mode is available only after the
    /// `private-key-control` ProtectedData domain opens.
    var privateKeyControlState: PrivateKeyControlState = .locked

    var authModeIfUnlocked: AuthenticationMode? {
        privateKeyControlState.authMode
    }

    /// Memory-only warning generated by post-unlock recovery and cleanup.
    var postUnlockRecoveryLoadWarning: String?

    func appendPostUnlockRecoveryLoadWarning(_ warning: String?) {
        guard let warning else { return }
        var diagnostics = postUnlockRecoveryLoadWarning?
            .components(separatedBy: "\n")
            .filter { !$0.isEmpty } ?? []
        for diagnostic in warning.components(separatedBy: "\n") {
            guard !diagnostic.isEmpty,
                  !diagnostics.contains(diagnostic) else {
                continue
            }
            diagnostics.append(diagnostic)
        }
        postUnlockRecoveryLoadWarning = diagnostics.isEmpty ? nil : diagnostics.joined(separator: "\n")
    }

    func clearPostUnlockRecoveryLoadWarning() {
        postUnlockRecoveryLoadWarning = nil
    }

    // MARK: - App Access Protection

    /// App launch/resume and App Data root-secret authentication policy — the
    /// **effective** policy, and the only one any authentication or gating call
    /// site should read.
    ///
    /// SECURITY-CRITICAL: while a policy switch is journaled but unconfirmed,
    /// the persisted root secret's Keychain access control may already carry
    /// either the committed policy's flags or the target's, and nothing can tell
    /// the two apart without an authenticated read. Answering with the stricter
    /// of the pair yields an `LAContext` that satisfies both access controls, so
    /// an interrupted switch can never leave the root secret unreachable
    /// (issue #747). It is also the "fail toward the stronger protection"
    /// direction: a passcode-satisfiable prompt is never offered for a gate that
    /// may already demand biometry.
    var appSessionAuthenticationPolicy: AppSessionAuthenticationPolicy {
        guard let pending = pendingAppSessionAuthenticationPolicySwitch else {
            return committedAppSessionAuthenticationPolicy
        }
        return .strictestPolicyForRootSecretReprotection(
            from: committedAppSessionAuthenticationPolicy,
            to: pending
        )
    }

    /// The last App Access Protection preference whose root-secret
    /// re-protection is known to have completed.
    private(set) var committedAppSessionAuthenticationPolicy: AppSessionAuthenticationPolicy {
        didSet {
            defaults.set(
                committedAppSessionAuthenticationPolicy.rawValue,
                forKey: Self.appSessionAuthenticationPolicyKey
            )
        }
    }

    /// Target of a switch that has reached the root-secret re-protection step
    /// and has not been confirmed complete. Surviving a launch means the process
    /// died inside that window, so the committed preference and the Keychain
    /// gate may disagree; `AppAccessPolicySwitchRecovery` converges them.
    private(set) var pendingAppSessionAuthenticationPolicySwitch: AppSessionAuthenticationPolicy? {
        didSet {
            guard let pending = pendingAppSessionAuthenticationPolicySwitch else {
                defaults.removeObject(forKey: Self.pendingAppSessionAuthenticationPolicySwitchKey)
                return
            }
            defaults.set(pending.rawValue, forKey: Self.pendingAppSessionAuthenticationPolicySwitchKey)
        }
    }

    /// Record the intent to move App Access Protection to `target`. Must be
    /// called before the persisted root secret's access control is rewritten —
    /// the journal is what makes the rewrite recoverable.
    func beginAppSessionAuthenticationPolicySwitch(to target: AppSessionAuthenticationPolicy) {
        pendingAppSessionAuthenticationPolicySwitch = target
    }

    /// Commit a switch whose root-secret re-protection has completed.
    ///
    /// SECURITY-CRITICAL ordering: the committed preference is written *before*
    /// the journal is cleared. A crash between the two leaves an open journal,
    /// which the next authenticated launch converges by re-protecting and
    /// committing again. The reverse order would reopen issue #747 — a cleared
    /// journal with an uncommitted preference is exactly the silent
    /// disagreement this journal exists to prevent, and once cleared nothing
    /// remains to detect it.
    func completeAppSessionAuthenticationPolicySwitch(to target: AppSessionAuthenticationPolicy) {
        committedAppSessionAuthenticationPolicy = target
        pendingAppSessionAuthenticationPolicySwitch = nil
    }

    // MARK: - UserDefaults Keys

    static let appSessionAuthenticationPolicyKey = "com.cypherair.preference.appSessionAuthenticationPolicy"
    static let pendingAppSessionAuthenticationPolicySwitchKey =
        "com.cypherair.preference.pendingAppSessionAuthenticationPolicySwitch"

    // MARK: - Initialization

    init(defaults: UserDefaults = .standard) {
        self.defaults = defaults

        let appSessionPolicyString = defaults.string(forKey: Self.appSessionAuthenticationPolicyKey)
            ?? AppSessionAuthenticationPolicy.userPresence.rawValue
        self.committedAppSessionAuthenticationPolicy = AppSessionAuthenticationPolicy(rawValue: appSessionPolicyString)
            ?? .userPresence
        self.pendingAppSessionAuthenticationPolicySwitch = defaults
            .string(forKey: Self.pendingAppSessionAuthenticationPolicySwitchKey)
            .flatMap(AppSessionAuthenticationPolicy.init(rawValue:))
    }

    func resetToFirstRunDefaults() {
        privateKeyControlState = .locked
        completeAppSessionAuthenticationPolicySwitch(to: .userPresence)

        for key in Self.resetPersistentKeys {
            defaults.removeObject(forKey: key)
        }
    }

    /// Available grace period values in seconds.
    static let validGracePeriodValues = [0, 60, 180, 300]

    private static var resetPersistentKeys: [String] {
        [
            appSessionAuthenticationPolicyKey,
            pendingAppSessionAuthenticationPolicySwitchKey
        ]
    }
}
