import Foundation

enum GuidedTutorialVersion {
    static let current = 2
}

enum GuidedTutorialCompletionState: Equatable {
    case neverCompleted
    case completedCurrentVersion
    case completedPreviousVersion
}

/// App-wide boot-safe configuration stored in UserDefaults.
@Observable
final class AppConfiguration {
    private let defaults: UserDefaults

    /// Private-key control state. The mode is available only after the
    /// `private-key-control` ProtectedData domain opens.
    var privateKeyControlState: PrivateKeyControlState = .locked

    var authModeIfUnlocked: AuthenticationMode? {
        privateKeyControlState.authMode
    }

    /// Memory-only warning generated by post-unlock private-key recovery.
    var postUnlockRecoveryLoadWarning: String?

    func clearPostUnlockRecoveryLoadWarning() {
        postUnlockRecoveryLoadWarning = nil
    }

    /// App launch/resume and App Data root-secret authentication policy.
    var appSessionAuthenticationPolicy: AppSessionAuthenticationPolicy {
        didSet {
            defaults.set(appSessionAuthenticationPolicy.rawValue, forKey: Self.appSessionAuthenticationPolicyKey)
        }
    }

    /// Incremented when decrypted content should be cleared (e.g., grace period expired).
    var contentClearGeneration: Int = 0

    /// Request that views holding decrypted content clear it.
    func requestContentClear() {
        contentClearGeneration += 1
    }

    /// Timestamp of last successful authentication, for grace period calculation.
    var lastAuthenticationDate: Date?

    // MARK: - UserDefaults Keys

    static let clipboardNoticeLegacyKey = "com.cypherair.preference.clipboardNotice"
    static let appSessionAuthenticationPolicyKey = "com.cypherair.preference.appSessionAuthenticationPolicy"
    private static let legacyRequireAuthOnLaunchKey = "com.cypherair.preference.requireAuthOnLaunch"

    // MARK: - Initialization

    init(defaults: UserDefaults = .standard) {
        self.defaults = defaults

        let appSessionPolicyString = defaults.string(forKey: Self.appSessionAuthenticationPolicyKey)
            ?? AppSessionAuthenticationPolicy.userPresence.rawValue
        self.appSessionAuthenticationPolicy = AppSessionAuthenticationPolicy(rawValue: appSessionPolicyString)
            ?? .userPresence
    }

    /// Record a successful authentication.
    func recordAuthentication() {
        lastAuthenticationDate = Date()
    }

    func resetToFirstRunDefaults() {
        privateKeyControlState = .locked
        appSessionAuthenticationPolicy = .userPresence
        contentClearGeneration += 1
        lastAuthenticationDate = nil

        for key in Self.resetPersistentKeys {
            defaults.removeObject(forKey: key)
        }
    }

    /// Available grace period options (in seconds).
    static let gracePeriodOptions: [(label: String, value: Int)] = [
        (String(localized: "grace.immediately", defaultValue: "Immediately"), 0),
        (String(localized: "grace.1min", defaultValue: "1 minute"), 60),
        (String(localized: "grace.3min", defaultValue: "3 minutes"), 180),
        (String(localized: "grace.5min", defaultValue: "5 minutes"), 300)
    ]

    private static var resetPersistentKeys: [String] {
        [
            clipboardNoticeLegacyKey,
            appSessionAuthenticationPolicyKey,
            legacyRequireAuthOnLaunchKey,
            AuthPreferences.authModeKey,
            AuthPreferences.rewrapInProgressKey,
            AuthPreferences.rewrapTargetModeKey,
            AuthPreferences.modifyExpiryInProgressKey,
            AuthPreferences.modifyExpiryFingerprintKey,
            "com.cypherair.preference.uiTestBypassAuthentication"
        ] + LegacyOrdinarySettingsStore.persistentKeys
    }
}
