import Foundation

enum GuidedTutorialVersion {
    static let current = 1
}

enum GuidedTutorialCompletionState: Equatable {
    case neverCompleted
    case completedCurrentVersion
    case completedPreviousVersion
}

/// App-wide boot-safe configuration stored in UserDefaults.
@Observable
final class AppConfiguration {
    private let defaults: UserDefaults

    /// Private-key control state. The mode is available only after the
    /// `private-key-control` ProtectedData domain opens.
    var privateKeyControlState: PrivateKeyControlState = .locked

    var authModeIfUnlocked: AuthenticationMode? {
        privateKeyControlState.authMode
    }

    /// Memory-only warning generated by post-unlock recovery and cleanup.
    var postUnlockRecoveryLoadWarning: String?

    func appendPostUnlockRecoveryLoadWarning(_ warning: String?) {
        guard let warning else { return }
        var diagnostics = postUnlockRecoveryLoadWarning?
            .components(separatedBy: "\n")
            .filter { !$0.isEmpty } ?? []
        for diagnostic in warning.components(separatedBy: "\n") {
            guard !diagnostic.isEmpty,
                  !diagnostics.contains(diagnostic) else {
                continue
            }
            diagnostics.append(diagnostic)
        }
        postUnlockRecoveryLoadWarning = diagnostics.isEmpty ? nil : diagnostics.joined(separator: "\n")
    }

    func clearPostUnlockRecoveryLoadWarning() {
        postUnlockRecoveryLoadWarning = nil
    }

    /// App launch/resume and App Data root-secret authentication policy.
    var appSessionAuthenticationPolicy: AppSessionAuthenticationPolicy {
        didSet {
            defaults.set(appSessionAuthenticationPolicy.rawValue, forKey: Self.appSessionAuthenticationPolicyKey)
        }
    }

    // MARK: - UserDefaults Keys

    static let appSessionAuthenticationPolicyKey = "com.cypherair.preference.appSessionAuthenticationPolicy"

    // MARK: - Initialization

    init(defaults: UserDefaults = .standard) {
        self.defaults = defaults

        let appSessionPolicyString = defaults.string(forKey: Self.appSessionAuthenticationPolicyKey)
            ?? AppSessionAuthenticationPolicy.userPresence.rawValue
        self.appSessionAuthenticationPolicy = AppSessionAuthenticationPolicy(rawValue: appSessionPolicyString)
            ?? .userPresence
    }

    func resetToFirstRunDefaults() {
        privateKeyControlState = .locked
        appSessionAuthenticationPolicy = .userPresence

        for key in Self.resetPersistentKeys {
            defaults.removeObject(forKey: key)
        }
    }

    /// Available grace period values in seconds.
    static let validGracePeriodValues = [0, 60, 180, 300]

    private static var resetPersistentKeys: [String] {
        [
            appSessionAuthenticationPolicyKey,
            "com.cypherair.preference.uiTestBypassAuthentication"
        ]
    }
}
