import XCTest
@testable import CypherAir

/// Swift-layer GnuPG interoperability tests (TESTING.md §7, Approach A).
///
/// These tests load pre-generated GnuPG fixture files from the test bundle
/// and verify that PgpEngine (via UniFFI FFI) can correctly process them.
/// This complements the Rust-layer tests in pgp-mobile/tests/gnupg_interop_tests.rs
/// by validating the full Rust→UniFFI→Swift chain on iOS simulator/device.
///
/// Fixture files are generated by pgp-mobile/tests/fixtures/generate_gpg_fixtures.sh
/// and copied into the test bundle via a Run Script build phase.
final class GnuPGInteropTests: XCTestCase {

    private var engine: PgpEngine!

    /// Expected plaintext matching what GnuPG encrypted (no trailing newline).
    /// Note: gpg_plaintext.txt has a trailing newline, but the encrypted fixtures
    /// were created with `echo -n` so the ciphertext does not contain it.
    /// We load the actual plaintext fixture and trim to match.
    private let expectedPlaintext = "Hello from GnuPG! This is a test message for Cypher Air interop testing."

    override func setUp() {
        super.setUp()
        engine = PgpEngine()
    }

    override func tearDown() {
        engine = nil
        super.tearDown()
    }

    // MARK: - Helpers

    /// Load a GnuPG fixture and convert armored data to binary.
    private func loadArmoredFixtureAsBinary(_ name: String, ext: String = "asc") throws -> Data {
        let armored = try FixtureLoader.loadData(name, ext: ext)
        return try engine.dearmor(armored: armored)
    }

    /// Load the GnuPG secret key (unprotected — generated with %no-protection).
    /// Returns binary cert data with unencrypted secret material, ready for decrypt().
    private func loadGpgSecretKey() throws -> Data {
        return try loadArmoredFixtureAsBinary("gpg_secretkey")
    }

    /// Load the GnuPG public key as binary.
    private func loadGpgPublicKey() throws -> Data {
        return try loadArmoredFixtureAsBinary("gpg_pubkey")
    }

    // MARK: - C3.1 Import GnuPG Public Key

    func test_c3_1_importGnuPGPublicKey_armored_parsesCorrectly() throws {
        let pubKeyData = try loadGpgPublicKey()
        let info = try engine.parseKeyInfo(keyData: pubKeyData)

        XCTAssertEqual(info.keyVersion, 4, "GnuPG key should be v4")
        XCTAssertEqual(info.profile, .universal, "GnuPG v4 key should be detected as Profile A (universal)")
        XCTAssertTrue(info.hasEncryptionSubkey, "GnuPG key should have an encryption subkey")
        XCTAssertFalse(info.isRevoked, "GnuPG key should not be revoked")
        XCTAssertFalse(info.isExpired, "GnuPG key should not be expired")
        XCTAssertFalse(info.fingerprint.isEmpty, "Fingerprint should not be empty")
    }

    // MARK: - C3.4 Decrypt GnuPG Encrypted Messages

    func test_c3_4_decryptGnuPGMessage_armored_matchesPlaintext() throws {
        let ciphertextArmored = try FixtureLoader.loadData("gpg_encrypted_message", ext: "asc")
        let ciphertext = try engine.dearmor(armored: ciphertextArmored)
        let secretKey = try loadGpgSecretKey()
        defer { var mutable = secretKey; mutable.resetBytes(in: 0..<mutable.count) }

        let result = try engine.decrypt(ciphertext: ciphertext, secretKeys: [secretKey], verificationKeys: [])
        defer { var plaintext = result.plaintext; plaintext.resetBytes(in: 0..<plaintext.count) }

        let decryptedText = String(data: result.plaintext, encoding: .utf8)
        XCTAssertEqual(decryptedText, expectedPlaintext, "Decrypted armored message should match GnuPG plaintext")
    }

    func test_c3_4_decryptGnuPGMessage_binary_matchesPlaintext() throws {
        let ciphertext = try FixtureLoader.loadData("gpg_encrypted_message", ext: "gpg")
        let secretKey = try loadGpgSecretKey()
        defer { var mutable = secretKey; mutable.resetBytes(in: 0..<mutable.count) }

        let result = try engine.decrypt(ciphertext: ciphertext, secretKeys: [secretKey], verificationKeys: [])
        defer { var plaintext = result.plaintext; plaintext.resetBytes(in: 0..<plaintext.count) }

        let decryptedText = String(data: result.plaintext, encoding: .utf8)
        XCTAssertEqual(decryptedText, expectedPlaintext, "Decrypted binary message should match GnuPG plaintext")
    }

    // MARK: - C3.5 Verify GnuPG Signatures

    func test_c3_5_verifyGnuPGCleartextSignature_returnsValid() throws {
        let signedMessage = try FixtureLoader.loadData("gpg_cleartext_signed", ext: "asc")
        let pubKey = try loadGpgPublicKey()

        let result = try engine.verifyCleartext(signedMessage: signedMessage, verificationKeys: [pubKey])

        XCTAssertEqual(result.status, .valid, "GnuPG cleartext signature should be valid")
        XCTAssertNotNil(result.signerFingerprint, "Signer fingerprint should be present")
        XCTAssertNotNil(result.content, "Signed content should be extracted")
    }

    func test_c3_5_verifyGnuPGDetachedSignature_armored_returnsValid() throws {
        let plaintext = try FixtureLoader.loadData("gpg_plaintext", ext: "txt")
        let signatureArmored = try FixtureLoader.loadData("gpg_detached_sig", ext: "asc")
        let signature = try engine.dearmor(armored: signatureArmored)
        let pubKey = try loadGpgPublicKey()

        let result = try engine.verifyDetached(data: plaintext, signature: signature, verificationKeys: [pubKey])

        XCTAssertEqual(result.status, .valid, "GnuPG armored detached signature should be valid")
    }

    func test_c3_5_verifyGnuPGDetachedSignature_binary_returnsValid() throws {
        let plaintext = try FixtureLoader.loadData("gpg_plaintext", ext: "txt")
        let signature = try FixtureLoader.loadData("gpg_detached_sig", ext: "sig")
        let pubKey = try loadGpgPublicKey()

        let result = try engine.verifyDetached(data: plaintext, signature: signature, verificationKeys: [pubKey])

        XCTAssertEqual(result.status, .valid, "GnuPG binary detached signature should be valid")
    }

    // MARK: - C3.6 Tamper Detection

    func test_c3_6_tamperedGnuPGCiphertext_throwsIntegrityError() throws {
        let tamperedCiphertext = try FixtureLoader.loadData("gpg_encrypted_tampered", ext: "gpg")
        let secretKey = try loadGpgSecretKey()
        defer { var mutable = secretKey; mutable.resetBytes(in: 0..<mutable.count) }

        XCTAssertThrowsError(
            try engine.decrypt(ciphertext: tamperedCiphertext, secretKeys: [secretKey], verificationKeys: []),
            "Decrypting tampered GnuPG ciphertext should throw an error"
        )
    }

    func test_c3_6_tamperedSequoiaCiphertext_forGnuPGKey_throwsIntegrityError() throws {
        let pubKey = try loadGpgPublicKey()
        let secretKey = try loadGpgSecretKey()
        defer { var mutable = secretKey; mutable.resetBytes(in: 0..<mutable.count) }

        // Encrypt with Sequoia to GnuPG key
        let plaintext = Data("Tamper test message".utf8)
        var ciphertext = try engine.encrypt(
            plaintext: plaintext,
            recipients: [pubKey],
            signingKey: nil,
            encryptToSelf: nil
        )

        // Need to dearmor since encrypt() returns armored
        var binaryCiphertext = try engine.dearmor(armored: ciphertext)
        ciphertext.resetBytes(in: 0..<ciphertext.count)

        // Flip one bit near the middle
        let midpoint = binaryCiphertext.count / 2
        binaryCiphertext[midpoint] ^= 0x01

        XCTAssertThrowsError(
            try engine.decrypt(ciphertext: binaryCiphertext, secretKeys: [secretKey], verificationKeys: []),
            "Decrypting tampered Sequoia ciphertext should throw an integrity error"
        )
    }

    // MARK: - C3.7 Full Round-Trip

    func test_c3_7_fullRoundtrip_encryptToGnuPGKey_thenDecrypt() throws {
        let pubKey = try loadGpgPublicKey()
        let secretKey = try loadGpgSecretKey()
        defer { var mutable = secretKey; mutable.resetBytes(in: 0..<mutable.count) }

        let originalText = "Round-trip test: Sequoia encrypt → GnuPG key → Sequoia decrypt"
        let plaintext = Data(originalText.utf8)

        // Encrypt to GnuPG public key
        let ciphertextArmored = try engine.encrypt(
            plaintext: plaintext,
            recipients: [pubKey],
            signingKey: nil,
            encryptToSelf: nil
        )
        let ciphertext = try engine.dearmor(armored: ciphertextArmored)

        // Decrypt with GnuPG secret key
        let result = try engine.decrypt(ciphertext: ciphertext, secretKeys: [secretKey], verificationKeys: [])
        defer { var decrypted = result.plaintext; decrypted.resetBytes(in: 0..<decrypted.count) }

        let decryptedText = String(data: result.plaintext, encoding: .utf8)
        XCTAssertEqual(decryptedText, originalText, "Round-trip plaintext should match original")
    }

    // MARK: - C2A.9 Compressed Message Decryption

    func test_c2a_9_decryptDeflateCompressedMessage_matchesPlaintext() throws {
        let ciphertextArmored = try FixtureLoader.loadData("gpg_encrypted_compressed_deflate", ext: "asc")
        let ciphertext = try engine.dearmor(armored: ciphertextArmored)
        let secretKey = try loadGpgSecretKey()
        defer { var mutable = secretKey; mutable.resetBytes(in: 0..<mutable.count) }

        let result = try engine.decrypt(ciphertext: ciphertext, secretKeys: [secretKey], verificationKeys: [])
        defer { var plaintext = result.plaintext; plaintext.resetBytes(in: 0..<plaintext.count) }

        let decryptedText = String(data: result.plaintext, encoding: .utf8)
        XCTAssertEqual(decryptedText, expectedPlaintext, "Decrypted DEFLATE-compressed message should match plaintext")
    }
}
